# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ZoomAutoUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1138, 908)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainWin = QtWidgets.QFrame(self.centralwidget)
        self.mainWin.setGeometry(QtCore.QRect(70, 70, 941, 791))
        self.mainWin.setStyleSheet("background-color: rgb(172, 172, 172);\n"
"border-radius:15px")
        self.mainWin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainWin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainWin.setObjectName("mainWin")
        self.titleBar = QtWidgets.QFrame(self.mainWin)
        self.titleBar.setGeometry(QtCore.QRect(0, 0, 941, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.titleBar.setFont(font)
        self.titleBar.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.titleBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleBar.setObjectName("titleBar")
        self.closeBtn = QtWidgets.QPushButton(self.titleBar)
        self.closeBtn.setGeometry(QtCore.QRect(910, 7, 16, 16))
        self.closeBtn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(255, 59, 41);\n"
"    border-radius:8px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(197, 37, 37);\n"
"    border-radius:8px\n"
"}")
        self.closeBtn.setText("")
        self.closeBtn.setObjectName("closeBtn")
        self.minBtn = QtWidgets.QPushButton(self.titleBar)
        self.minBtn.setGeometry(QtCore.QRect(880, 7, 16, 16))
        self.minBtn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(255, 220, 17);\n"
"    border-radius:8px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(212, 182, 28);\n"
"    border-radius:8px\n"
"}")
        self.minBtn.setText("")
        self.minBtn.setObjectName("minBtn")
        self.appName = QtWidgets.QLabel(self.titleBar)
        self.appName.setGeometry(QtCore.QRect(40, 0, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.appName.setFont(font)
        self.appName.setObjectName("appName")
        self.appIcon = QtWidgets.QPushButton(self.titleBar)
        self.appIcon.setGeometry(QtCore.QRect(5, 0, 30, 30))
        self.appIcon.setText("")
        self.appIcon.setObjectName("appIcon")
        self.tableWidget = QtWidgets.QTableWidget(self.mainWin)
        self.tableWidget.setGeometry(QtCore.QRect(30, 70, 875, 651))
        self.tableWidget.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.saveBtn = QtWidgets.QPushButton(self.mainWin)
        self.saveBtn.setGeometry(QtCore.QRect(810, 740, 61, 28))
        self.saveBtn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(85, 255, 127);\n"
"    border-radius:12px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(66, 198, 97);\n"
"    border-radius:12px\n"
"}\n"
"")
        self.saveBtn.setObjectName("saveBtn")
        self.addBtn = QtWidgets.QPushButton(self.mainWin)
        self.addBtn.setGeometry(QtCore.QRect(670, 740, 121, 28))
        self.addBtn.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(85, 255, 127);\n"
"    border-radius:12px\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(66, 198, 97);\n"
"    border-radius:12px\n"
"}\n"
"")
        self.addBtn.setObjectName("addBtn")
        self.displayTime = QtWidgets.QLabel(self.mainWin)
        self.displayTime.setGeometry(QtCore.QRect(30, 40, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.displayTime.setFont(font)
        self.displayTime.setObjectName("displayTime")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.appName.setText(_translate("MainWindow", "ZoomBot"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Password"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Date and Time"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "No Audio"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "No Video"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Delete"))
        self.saveBtn.setText(_translate("MainWindow", "Save"))
        self.addBtn.setText(_translate("MainWindow", "Add New Meeting"))
        self.displayTime.setText(_translate("MainWindow", "Time : 01-Jan , 12:00:00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
